
create_driver pcie_status_amm_driver

set_sw_property hw_class_name pcie_status_amm
set_sw_property version 1.0
set_sw_property bsp_subdirectory drivers
set_sw_property min_compatible_hw_version 1.0

add_sw_property include_source inc/pcie_status_amm.h

add_sw_property c_source src/pcie_status_amm.c

add_sw_property supported_bsp_type HAL
